// variables js pour démo version statique (hébergement sans BDD)

export const galery = [

    {
        "video_id" : "1",
        "pseudo": "NinaGlide",
        "title": "User1V1.mp4",
        "trick_name" : "Hardflip",
        "publication_date" : "2024-05-31 12:55:54",
        "reaction_total" : 67,
    },
    {
        "video_id" : "2",
        "pseudo": "NinaGlide",
        "title": "User1V2.mp4",
        "trick_name" : "Tailslide",
        "publication_date" : "2024-05-25 00:06:46",
        "reaction_total" : 42,
    },
    {
        "video_id" : "3",
        "pseudo": "LéoSpeedster",
        "title": "User2V1.mp4",
        "trick_name" : "Nosegrind",
        "publication_date" : "2024-05-23 06:53:09",
        "reaction_total" : 38,
    },
    {
        "video_id" : "4",
        "pseudo": "LéoSpeedster",
        "title": "User2V2.mp4",
        "trick_name" : "Nosegrind",
        "publication_date" : "2024-05-12 07:04:04",
        "reaction_total" : 50,
    },
    {
        "video_id" : "5",
        "pseudo": "LéoSpeedster",
        "title": "User2V3.mp4",
        "trick_name" : "Kickflip",
        "publication_date" : "2024-05-09 16:06:27",
        "reaction_total" : 5,
    },
    {
        "video_id" : "6",
        "pseudo": "TomRoll",
        "title": "User3V1.mp4",
        "trick_name" : "Kickflip",
        "publication_date" : "2024-05-05 15:11:09",
        "reaction_total" : 55,
    },
    {
        "video_id" : "7",
        "pseudo": "TomRoll",
        "title": "User3V2.mp4",
        "trick_name" : "Kickflip",
        "publication_date" : "2024-05-04 22:50:29",
        "reaction_total" : 25,
    },
    {
        "video_id" : "8",
        "pseudo": "TomRoll",
        "title": "User3V3.mp4",
        "trick_name" : "Smith",
        "publication_date" : "2024-04-29 13:34:44",
        "reaction_total" : 29,
    },
    {
        "video_id" : "9",
        "pseudo": "TomRoll",
        "title": "User3V4.mp4",
        "trick_name" : "Smith",
        "publication_date" : "2024-04-23 06:21:40",
        "reaction_total" : 14,
    },
    {
        "video_id" : "10",
        "pseudo": "TomRoll",
        "title": "User3V5.mp4",
        "trick_name" : "Crooked",
        "publication_date" : "2024-04-06 02:30:54",
        "reaction_total" : 10,
    },
    {
        "video_id" : "11",
        "pseudo": "TomRoll",
        "title": "User4V1.mp4",
        "trick_name" : "50-50",
        "publication_date" : "2024-04-02 22:47:18",
        "reaction_total" : 100,
    },

];